apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-kumu-live
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kumumedia/kumu-k8s-helmchart.git'
    path: api-kumu-live
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/stage.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kumuapi
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
